### ISSUE TITLE
Query Regarding implementation

### ISSUE THREAD

**Issue by minesh94** [tttthomasssss/apt-toolkit#2]
I have some queries related to paper. It would be really helpful if you would answer them.

1. You have taken SPMI as weights. Also it has been mentioned in the paper that we can take probabilities and counts as well. If we take probabilities how do you ensure that the composed vector weights won't go more than 1 or violate the probabilistic space of lying between 0 and 1.
2. Also for count vectors, do we perform normalization or use counts as they are.
3. Also why do you use vector space and not sets.

**Comment by tttthomasssss** [comment]
Just adding the answers I sent you via email here as well in case anybody else has similar queries.

ad 1: You would need to re-normalise the composed APTs in order to get a probability distribution again. 

ad 2: We used raw counts (and subsequently transformed them to SPPMI weights). Its perfectly possible to normalise the counts though.

ad 3: Sets are unordered, however with distributional composition you need to make sure to compose the corresponding dimensions of two APTs, thus we used a vector space as is common in distributional semantics research.
